### ISSUE TITLE
You can’t use this version of the application “Comic2Books” with this version of macOS.

### ISSUE THREAD

**Issue by Jsaeron** [manueldidonna/comic2books#1]
You can’t use this version of the application “Comic2Books” with this version of macOS.

我的 macOS系统版本 Sonoma Version 14.0 不支持吗？

**Comment by manueldidonna** [comment]
Try with the latest release and let me know. Don't forget to put the app in the Applications folder
https://github.com/manueldidonna/comic2books/releases/tag/0.2
