### ISSUE TITLE
I want to be able to set an arbitrary resolution.

### ISSUE THREAD

**Issue by kingtosh** [manueldidonna/comic2books#3]
I want to be able to set an arbitrary resolution.
The required resolution setting is not in the menu.

**Comment by manueldidonna** [comment]
I should open a PR for the library's repository that my application uses for conversion. In the meantime, could you tell me more about your use case?

**Comment by akumathedyn123** [comment]
@kingtosh https://github.com/akumathedyn123/python-epub-extractor-epub2txt
